apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ubuntu-new
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/nicolasjulian/KubeVirt.git
    targetRevision: HEAD
    path: ubuntu
  destination:
    name: in-cluster 
    namespace: default
  syncPolicy:
    automated: {}      
