apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-hostpath-node4
  annotations:
    openebs.io/cas-type: local
    cas.openebs.io/config: |
      - name: StorageType
        value: hostpath
      - name: BasePath
        value: /var/local-hostpath
    cas.openebs.io/config: |
      - name: kubernetes.io/hostname
        value: "node4"
provisioner: openebs.io/local
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: True
